# Generated by Django 5.1.4 on 2024-12-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_apps_delete_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='app_points',
            field=models.IntegerField(default=0),
        ),
    ]
