# Generated by Django 5.1.4 on 2024-12-29 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_apps_app_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apps',
            name='created_by',
        ),
    ]
