# Generated by Django 5.1.4 on 2024-12-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_apps_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='app_logo',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
