# Generated by Django 5.1.4 on 2024-12-30 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_apps_app_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='app_logo',
            field=models.ImageField(blank=True, default='default-image-5-1.jpg', null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='TaskImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='default-image-5-1.jpg/')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_images', to='api.apps')),
            ],
        ),
    ]
